name: autoupdate
on:
  push:
    branches:
      - 'main'

jobs:
  update-branches:
    name: Update branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update branches
        uses: brainly/action-autoupdate-branch@2.0.0
        id: autoUpdateBranch
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          requiredApprovals: 0
